### ISSUE TITLE
i18n: Default to English if the system locale is not supported

### ISSUE THREAD

**Issue by sorenabell** [open-contracting/spoonbill#135]
Some of the CLI functionality does not work with Python 3.6

```
(venv) Olegs-MacBook-Pro:spoon_bill oleg$ pip install spoonbill
Collecting spoonbill
  Using cached spoonbill-1.0.3b2-py3-none-any.whl (61 kB)
Collecting jsonref
  Using cached jsonref-0.2-py3-none-any.whl (9.3 kB)
Collecting ijson>=2.5
  Using cached ijson-3.1.4-cp36-cp36m-macosx_10_9_x86_64.whl (52 kB)
Collecting click-logging
  Using cached click_logging-1.0.1-py2.py3-none-any.whl (6.6 kB)
Collecting flatten-dict
  Using cached flatten_dict-0.4.0-py2.py3-none-any.whl (9.5 kB)
Collecting ocdsextensionregistry
  Using cached ocdsextensionregistry-0.1.4-py3-none-any.whl (26 kB)
Collecting xlsxwriter
  Using cached XlsxWriter-1.4.3-py2.py3-none-any.whl (149 kB)
Collecting jsonpointer
  Using cached jsonpointer-2.1-py2.py3-none-any.whl (7.4 kB)
Collecting dataclasses
  Using cached dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting ocdskit
  Using cached ocdskit-1.0.0-py3-none-any.whl (35 kB)
Collecting click
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting importlib-metadata
  Using cached importlib_metadata-4.5.0-py3-none-any.whl (17 kB)
Collecting six<2.0,>=1.12
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting typing-extensions>=3.6.4
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting zipp>=0.5
  Using cached zipp-3.4.1-py3-none-any.whl (5.2 kB)
Collecting json-merge-patch
  Using cached json-merge-patch-0.2.tar.gz (3.1 kB)
Collecting requests-cache
  Using cached requests_cache-0.6.4-py2.py3-none-any.whl (28 kB)
Collecting ocdsmerge>=0.6
  Using cached ocdsmerge-0.6.6-py3-none-any.whl (10 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting itsdangerous
  Using cached itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting url-normalize>=1.4
  Using cached url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Using legacy 'setup.py install' for json-merge-patch, since package 'wheel' is not installed.
Installing collected packages: urllib3, six, idna, chardet, certifi, zipp, url-normalize, typing-extensions, requests, itsdangerous, requests-cache, jsonref, json-merge-patch, importlib-metadata, ocdsmerge, ocdsextensionregistry, ijson, click, xlsxwriter, ocdskit, jsonpointer, flatten-dict, dataclasses, click-logging, spoonbill
    Running setup.py install for json-merge-patch ... done
Successfully installed certifi-2021.5.30 chardet-4.0.0 click-8.0.1 click-logging-1.0.1 dataclasses-0.8 flatten-dict-0.4.0 idna-2.10 ijson-3.1.4 importlib-metadata-4.5.0 itsdangerous-2.0.1 json-merge-patch-0.2 jsonpointer-2.1 jsonref-0.2 ocdsextensionregistry-0.1.4 ocdskit-1.0.0 ocdsmerge-0.6.6 requests-2.25.1 requests-cache-0.6.4 six-1.16.0 spoonbill-1.0.3b2 typing-extensions-3.10.0.0 url-normalize-1.4.3 urllib3-1.26.5 xlsxwriter-1.4.3 zipp-3.4.1



(venv) Olegs-MacBook-Pro:spoon_bill oleg$ spoonbill
Traceback (most recent call last):
  File "/Users/oleg/PycharmProjects/spoon_bill/venv/bin/spoonbill", line 5, in <module>
    from spoonbill.cli import cli
  File "/Users/oleg/PycharmProjects/spoon_bill/venv/lib/python3.6/site-packages/spoonbill/cli.py", line 22, in <module>
    ANALYZED_LABEL = _("  Processed {} objects")
  File "/Users/oleg/PycharmProjects/spoon_bill/venv/lib/python3.6/site-packages/spoonbill/i18n.py", line 24, in translate
    translator = _translation(lang)
  File "/Users/oleg/PycharmProjects/spoon_bill/venv/lib/python3.6/site-packages/spoonbill/i18n.py", line 32, in _translation
    return gettext.translation(DOMAIN, LOCALEDIR, languages=[lang], fallback=None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/gettext.py", line 514, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'spoonbill'
```

**Comment by jpmckinney** [comment]
I can reproduce with:

```
env LANG=ru_RU spoonbill
```

I don't think this is limited to Python 3.6. The logic should be that if a locale is not supported, it defaults to English.
