### ISSUE TITLE
spoonbill should either recover or display an error message if JsonRefError encountered

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill#160]
```
curl -o ocds-03ad3f-394288-1.json https://contrataciones.gov.py/datos/api/v3/doc/ocds/record/ocds-03ad3f-394288-1
spoonbill ocds-03ad3f-394288-1.json
```

(Also attached as .txt)

```
State file not supplied, going to analyze input file first
Analyze options:
 - threshold                      => 5
 - language                       => en
Processing file: ocds-03ad3f-394288-1.json
  [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]  0/7777    0%Input file is record package
No schema provided, using version 1__1__5

Traceback (most recent call last):
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/proxytypes.py", line 252, in __subject__
    return self.cache
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/proxytypes.py", line 176, in __getattribute__
    return _oga(self, attr)
AttributeError: 'JsonRef' object has no attribute 'cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/jsonref.py", line 178, in callback
    base_doc = self.loader(uri)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/jsonref.py", line 299, in __call__
    result = self.get_remote_json(uri, **kwargs)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/jsonref.py", line 316, in get_remote_json
    result = json.loads(urlopen(uri).read().decode("utf-8"), **kwargs)
  File "/Users/james/.pyenv/versions/3.6.11/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/james/.pyenv/versions/3.6.11/lib/python3.6/urllib/request.py", line 511, in open
    req = Request(fullurl, data)
  File "/Users/james/.pyenv/versions/3.6.11/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/Users/james/.pyenv/versions/3.6.11/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/Users/james/.pyenv/versions/3.6.11/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/james/.pyenv/versions/spoonbill/bin/spoonbill", line 11, in <module>
    load_entry_point('spoonbill', 'console_scripts', 'spoonbill')()
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/james/Sites/remote/open-contracting/spoonbill/spoonbill/cli.py", line 230, in cli
    for read, number in analyzer.analyze_file(filename, with_preview=True):
  File "/Users/james/Sites/remote/open-contracting/spoonbill/spoonbill/__init__.py", line 72, in analyze_file
    table_threshold=self.table_threshold,
  File "/Users/james/Sites/remote/open-contracting/spoonbill/spoonbill/stats.py", line 69, in __init__
    self.parse_schema()
  File "/Users/james/Sites/remote/open-contracting/spoonbill/spoonbill/stats.py", line 105, in parse_schema
    if prop.get("deprecated"):
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/proxytypes.py", line 175, in __getattribute__
    return getattr(self.__subject__, attr)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/proxytypes.py", line 176, in __getattribute__
    return _oga(self, attr)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/proxytypes.py", line 134, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/proxytypes.py", line 254, in __subject__
    self.cache = super(LazyProxy, self).__subject__
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/proxytypes.py", line 134, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/proxytypes.py", line 240, in __subject__
    return self.callback()
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/proxytypes.py", line 134, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/jsonref.py", line 180, in callback
    self._error("%s: %s" % (e.__class__.__name__, unicode(e)), cause=e)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/proxytypes.py", line 134, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/james/.pyenv/versions/3.6.11/envs/spoonbill/lib/python3.6/site-packages/jsonref.py", line 229, in _error
    cause=cause,
jsonref.JsonRefError: ValueError: unknown url type: ''
```

[ocds-03ad3f-394288-1.json.txt](https://github.com/open-contracting/spoonbill/files/6823587/ocds-03ad3f-394288-1.json.txt)

**Comment by jpmckinney** [comment]
`parse_schema` is receiving `{'$ref': '#/definitions/record'}` in `self.schema`. I don't know if that is related to the issue.

**Comment by jpmckinney** [comment]
Hmm, yes, I think the problem is that the call to `self.schema = jsonref.JsonRef.replace_refs(self.schema)` in `DataPreprocessor.parse_schema` is too late. In `FileAnalyzer.parse_schema`, schema gets set to that JSON Schema fragment `{'$ref': '#/definitions/record'}`. Since that schema no longer has `/definitions`, it is unresolvable. I think it's necessary to call `schema = jsonref.JsonRef.replace_refs(schema)` in `FileAnalyzer.parse_schema`, and to remove the call in `DataPreprocessor.parse_schema`.
