### ISSUE TITLE
Error with data from UK Find a Tender Service

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/spoonbill#195]
I tried to use the following command to flatten some data from UK Find a Tender Service: `spoonbill release-package.json`

The data has some minor structure and format issues, but nothing major.

[Data](https://drive.google.com/file/d/1vWvVRplw8EbOEOIesJhusDHY4P-kO1Rf/view?usp=sharing)
[DRT results](https://standard.open-contracting.org/review/data/8a061934-5970-419e-a098-bf311c51b384)

Spoonbill output and traceback:

```
State file not supplied, going to analyze input file first
Analyze options:
 - threshold                      => 5
 - language                       => en
Processing file: release-package.json
Input file is release package
No schema provided, using version 1__1__5
  Processed 3 objects  []  65536/5970561    1%  00:02:17
Traceback (most recent call last):
  File "/usr/local/bin/spoonbill", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/spoonbill/cli.py", line 230, in cli
    for read, number in analyzer.analyze_file(filename, with_preview=False):
  File "/usr/local/lib/python3.7/dist-packages/spoonbill/__init__.py", line 88, in analyze_file
    for count in self.spec.process_items(items):
  File "/usr/local/lib/python3.7/dist-packages/spoonbill/stats.py", line 321, in process_items
    self.inc_table_rows(item, rows, parent_key, record)
  File "/usr/local/lib/python3.7/dist-packages/spoonbill/stats.py", line 244, in inc_table_rows
    self.add_preview_row(rows, record.get("id", ""), parent_key)
  File "/usr/local/lib/python3.7/dist-packages/spoonbill/stats.py", line 237, in add_preview_row
    row = rows.new_row(table, item_id).as_dict()
  File "/usr/local/lib/python3.7/dist-packages/spoonbill/rowdata.py", line 65, in new_row
    while parent_row.parent:
AttributeError: 'str' object has no attribute 'parent'
```

**Comment by jpmckinney** [comment]
@sorenabell Can you provide an estimate for fixing this bug? It is a blocker for launch (see also the update to open-contracting/spoonbill-web#353).

**Comment by sorenabell** [comment]
@jpmckinney From 1 to 3 days depending on what is the source of the issue.

**Comment by sorenabell** [comment]
Great. 
@jpmckinney should we deploy updates to production or you would take care of that?

**Comment by yolile** [comment]
I tested them in production now and the bug is still there, so I guess these changes weren't part of https://github.com/open-contracting/spoonbill-web/pull/394
